name: check_python_version

on:
  push:
    branches:
      - check_python_version

jobs:
  build:
    
    runs-on: macos-latest

    steps:
      - name: set_up_python
        uses: actions/setup-python@v3
        with: 
          python-version: "3.11"
      - name: pip_update
        run: |
          python -m pip install --upgrade pip
      - name: python_version
        run: |
          python --version
