name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
      - name: set_up_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip_update
        run: |
          python -m pip install --upgrade pip

      - name: run_app
        run: python app.py

      - name: flake8&pytest_install
        run: |
          python -m pip install flake8
          #python -m pip install 

      - name: python_version
        run: |
          python --version
          pip --version

      - name: flake8_code_analysis
        run: |
          flake8 .

      - name: pytest_tests
        run: |
          python -m unittest test.py
